/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoyreplicacionpa;

import java.awt.Image;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmEmpleado extends javax.swing.JFrame {

    private Icon icono;
    private ImageIcon imagen;
    
    public FrmEmpleado() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.pintarImagen(this.lblFondo,  "src/Imagenes/pollo-corriendo-pollo.gif");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID_Empleado = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        txtID_Empleado = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTEmpleado = new javax.swing.JTable();
        txtCargo = new javax.swing.JTextField();
        lblTelefono1 = new javax.swing.JLabel();
        lblObservacion = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID_Empleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblID_Empleado.setText("ID");
        getContentPane().add(lblID_Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lblApellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblApellido.setText("Apellido");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtID_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID_EmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtID_Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 7, 255, -1));
        getContentPane().add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 255, -1));

        txtNombre.setBackground(new java.awt.Color(234, 234, 234));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 255, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 255, -1));

        btnNuevo.setBackground(new java.awt.Color(36, 133, 19));
        btnNuevo.setForeground(new java.awt.Color(153, 255, 102));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 92, -1));

        btnEnviar.setBackground(new java.awt.Color(36, 133, 19));
        btnEnviar.setForeground(new java.awt.Color(153, 255, 102));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 92, -1));

        btnEliminar.setBackground(new java.awt.Color(36, 133, 19));
        btnEliminar.setForeground(new java.awt.Color(153, 255, 102));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 93, -1));

        btnActualizar.setBackground(new java.awt.Color(36, 133, 19));
        btnActualizar.setForeground(new java.awt.Color(153, 255, 102));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 93, -1));

        jTEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Cargo", "Sueldo"
            }
        ));
        jTEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTEmpleado);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 510, 145));
        getContentPane().add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 255, -1));

        lblTelefono1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTelefono1.setText("Cargo");
        getContentPane().add(lblTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblObservacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblObservacion.setText("Sueldo");
        getContentPane().add(lblObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 80, -1));

        lblFondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtID_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID_EmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID_EmpleadoActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        this.enviar();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jTEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTEmpleadoMouseClicked
        this.mouseclick();
    }//GEN-LAST:event_jTEmpleadoMouseClicked

private void nuevo(){
    try{
       EmpleadoBeans Emp=new EmpleadoBeans();
       txtID_Empleado.setText(""+Emp.Incremento_Empleado()); 
       txtNombre.setText("");
       txtApellido.setText("");
       txtCargo.setText("");
       txtSueldo.setText("");

                     
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error..."+ e.toString());  
    }
}
    
    private void enviar() {
    try {
        EmpleadoBeans Emp = new EmpleadoBeans();
        Emp.setID_empleado(Integer.parseInt(txtID_Empleado.getText()));
        Emp.setNombre(txtNombre.getText());
        Emp.setApellido(txtApellido.getText());
        Emp.setCargo(txtCargo.getText());
        Emp.setSueldo(txtSueldo.getText());
        Emp.Insertar_Empleado();
        this.mostrar(jTEmpleado,"Select * from Empleado");
        
        JOptionPane.showMessageDialog(null, "La información se ha guardado con éxito");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error de la transacción... RollBack: " + e.toString());
    }
}
    


private void mostrar(javax.swing.JTable JT, String sql){
    try{
        ClienteBeans Cl = new ClienteBeans();
        ResultSet rs;
        DefaultTableModel modelo=new DefaultTableModel();
        JT.setModel(modelo);
        rs=Cl.ConsultarTabla(sql);
        ResultSetMetaData rsMd;
        rsMd = rs.getMetaData();
        int cantcolumnas=rsMd.getColumnCount();
        
        for (int i = 1; i <= cantcolumnas; i++) {
            modelo.addColumn(rsMd.getColumnLabel(i));
        }
        while(rs.next()){
            Object [] columna=new Object[cantcolumnas];
            for(int i = 0; i < cantcolumnas; i++){
                columna[i]=rs.getObject(i+1);
            }
            modelo.addRow(columna);
        }
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error"+ e.toString());
    }

}
    private void mouseclick(){
     
    int fila = jTEmpleado.getSelectedRow();
    txtID_Empleado.setText(jTEmpleado.getModel().getValueAt(fila, 0).toString());
    txtNombre.setText(jTEmpleado.getModel().getValueAt(fila, 1).toString());
    txtApellido.setText(jTEmpleado.getModel().getValueAt(fila, 2).toString());
    txtCargo.setText(jTEmpleado.getModel().getValueAt(fila, 3).toString());
    txtSueldo.setText(jTEmpleado.getModel().getValueAt(fila, 4).toString());
     
}
    
    private  void pintarImagen(JLabel lbl, String ruta){
    
           this.imagen = new ImageIcon(ruta);
           this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));
           lbl.setIcon(this.icono);
           this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTEmpleado;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblID_Empleado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblObservacion;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtID_Empleado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
